#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# generate-agent.sh — Generate AI agent instruction files for a project
#
# Usage: generate-agent.sh <agent-name> <project-dir> <config-file>
#
# Agents:
#   claude   → $PROJECT_DIR/CLAUDE.md
#   copilot  → $PROJECT_DIR/.github/copilot-instructions.md
#   cursor   → $PROJECT_DIR/.cursor/rules/lifecycle.mdc
#
# Environment variables:
#   LIFECYCLE_DIR  — Path to the ai-dev-lifecycle repo (default: ~/.ai-dev-lifecycle)
# -----------------------------------------------------------------------------

LIFECYCLE_DIR="${LIFECYCLE_DIR:-$HOME/.ai-dev-lifecycle}"

AGENT_NAME="${1:-}"
PROJECT_DIR="${2:-}"
CONFIG_FILE="${3:-}"

# ── Validation ────────────────────────────────────────────────────────────────
if [[ -z "$AGENT_NAME" || -z "$PROJECT_DIR" || -z "$CONFIG_FILE" ]]; then
  echo "Usage: generate-agent.sh <agent-name> <project-dir> <config-file>" >&2
  echo "  agent-name  : claude | copilot | cursor" >&2
  exit 1
fi

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "[error] Config file not found: $CONFIG_FILE" >&2
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "[error] 'jq' is required but not installed." >&2
  exit 1
fi

AGENTS_DIR="$LIFECYCLE_DIR/agents"
RULES_DIR="$AGENTS_DIR/rules"
TEMPLATE_FILE="$AGENTS_DIR/$AGENT_NAME/template.md"

if [[ ! -f "$TEMPLATE_FILE" ]]; then
  echo "[error] Template not found for agent '$AGENT_NAME': $TEMPLATE_FILE" >&2
  exit 1
fi

# ── Determine output path ─────────────────────────────────────────────────────
case "$AGENT_NAME" in
  claude)
    OUTPUT_FILE="$PROJECT_DIR/CLAUDE.md"
    ;;
  copilot)
    OUTPUT_FILE="$PROJECT_DIR/.github/copilot-instructions.md"
    ;;
  cursor)
    OUTPUT_FILE="$PROJECT_DIR/.cursor/rules/lifecycle.mdc"
    ;;
  *)
    echo "[error] Unknown agent: $AGENT_NAME (expected: claude, copilot, cursor)" >&2
    exit 1
    ;;
esac

# ── Read config values ────────────────────────────────────────────────────────
PROJECT_NAME="$(jq -r '.project.name // "Unknown Project"' "$CONFIG_FILE")"
LANGUAGE="$(jq -r '.project.language // "csharp"' "$CONFIG_FILE")"
DESCRIPTION="$(jq -r '.project.description // ""' "$CONFIG_FILE")"

# Read the list of enabled rules for this agent
ENABLED_RULES="$(jq -r ".agents[\"$AGENT_NAME\"].rules // [] | .[]" "$CONFIG_FILE" 2>/dev/null || true)"

# ── Collect enabled modules (for context) ─────────────────────────────────────
ENABLED_MODULES="$(jq -r '[.modules | to_entries[] | select(.value.enabled == true) | .key] | join(", ")' "$CONFIG_FILE")"

# ── Assemble rules content ────────────────────────────────────────────────────
RULES_CONTENT=""

while IFS= read -r rule_name; do
  [[ -z "$rule_name" ]] && continue

  rule_file="$RULES_DIR/${rule_name}.md"

  if [[ ! -f "$rule_file" ]]; then
    echo "[warn]  Rule file not found, skipping: $rule_file"
    continue
  fi

  echo "[info]  Including rule: $rule_name"

  rule_content="$(cat "$rule_file")"

  if [[ -n "$RULES_CONTENT" ]]; then
    RULES_CONTENT="${RULES_CONTENT}"$'\n\n---\n\n'"${rule_content}"
  else
    RULES_CONTENT="${rule_content}"
  fi

done <<< "$ENABLED_RULES"

if [[ -z "$RULES_CONTENT" ]]; then
  RULES_CONTENT="*No rules configured for this agent. Add rules to .devlifecycle.json under agents.$AGENT_NAME.rules.*"
fi

# ── Build language-specific command hints ─────────────────────────────────────
case "$LANGUAGE" in
  csharp)
    BUILD_CMD="dotnet build"
    TEST_CMD="dotnet test"
    LINT_CMD="dotnet format --verify-no-changes"
    ;;
  typescript)
    BUILD_CMD="npm run build"
    TEST_CMD="npm test"
    LINT_CMD="npm run lint"
    ;;
  *)
    BUILD_CMD="<build command>"
    TEST_CMD="<test command>"
    LINT_CMD="<lint command>"
    ;;
esac

# ── Load template and substitute placeholders ─────────────────────────────────
TEMPLATE_CONTENT="$(cat "$TEMPLATE_FILE")"

OUTPUT_CONTENT="${TEMPLATE_CONTENT}"
OUTPUT_CONTENT="${OUTPUT_CONTENT//\{\{PROJECT_NAME\}\}/$PROJECT_NAME}"
OUTPUT_CONTENT="${OUTPUT_CONTENT//\{\{DESCRIPTION\}\}/$DESCRIPTION}"
OUTPUT_CONTENT="${OUTPUT_CONTENT//\{\{LANGUAGE\}\}/$LANGUAGE}"
OUTPUT_CONTENT="${OUTPUT_CONTENT//\{\{ENABLED_MODULES\}\}/$ENABLED_MODULES}"
OUTPUT_CONTENT="${OUTPUT_CONTENT//\{\{BUILD_CMD\}\}/$BUILD_CMD}"
OUTPUT_CONTENT="${OUTPUT_CONTENT//\{\{TEST_CMD\}\}/$TEST_CMD}"
OUTPUT_CONTENT="${OUTPUT_CONTENT//\{\{LINT_CMD\}\}/$LINT_CMD}"
# Use Python3 for RULES_CONTENT substitution — bash parameter expansion treats '&'
# as a backreference to the matched string, corrupting any '&&' in rule content.
OUTPUT_CONTENT="$(python3 -c "
import sys
content = sys.argv[1]
rules   = sys.argv[2]
print(content.replace('{{RULES_CONTENT}}', rules), end='')
" "$OUTPUT_CONTENT" "$RULES_CONTENT")"

# ── Write output ──────────────────────────────────────────────────────────────
OUTPUT_DIR="$(dirname "$OUTPUT_FILE")"
mkdir -p "$OUTPUT_DIR"

HEADER="<!-- Auto-generated by ai-dev-lifecycle. Do not edit manually. -->
<!-- Source: https://github.com/goeke-m/ai-dev-lifecycle -->
<!-- Regenerate: bash \$LIFECYCLE_DIR/scripts/generate-agent.sh $AGENT_NAME $PROJECT_DIR $CONFIG_FILE -->

"

printf '%s%s\n' "$HEADER" "$OUTPUT_CONTENT" > "$OUTPUT_FILE"

echo "[ok]    Generated: $OUTPUT_FILE"
